version: '3'

services:
  db:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
  app:
    build:
      context: ./server
    image: myserver:latest
    container_name: myserver
    ports:
      - 8000:8000
    volumes:
      - ./server:/app:ro
      - ./data:/data
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src
