version: '3'

services:
  db:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: memo
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - 6379:6379
  app:
    build:
      context: ./server
    image: myserver:latest
    container_name: myapp
    ports:
      - 8000:8000
    volumes:
      - ./server:/app:ro
      - ./data:/data
    env_file:
      - ./server/.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir src
